version: '3'

services:
  php-app:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql-db

  mysql-db:
    build:
      context: .
      dockerfile: docker/mysql.dockerfile
    ports:
      - "3306:3306"