version: '3'

services:
  web:
    container_name: apache-new
    image: httpd:latest 
    ports:
      - "8080:80"
    # volumes:
    #   - ./apache2/apache-config.conf:/usr/local/apache2/conf/httpd.conf  
    depends_on:
      - laravel-app

  laravel-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - mysql-db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql-db
      DB_PORT: 4306
      DB_DATABASE: liberty_insurance_portal
      DB_USERNAME: root
      DB_PASSWORD: 

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: liberty_insurance_portal
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
