  laravel-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8082:80"

    environment:
      # DB_CONNECTION: mysql
      # DB_HOST: mysql-db
      # DB_PORT: 4306
      DB_DATABASE: liberty_insurance_portal
      DB_USERNAME: root
      DB_PASSWORD: 1234


